import DiagramNode, { Arrow, FlowRow } from '../DiagramNode';

const aesInfo = {
  plaintext: {
    title: '128-bit Plaintext State',
    description: 'AES operates on a 4×4 matrix of bytes called the "State". Unlike DES which uses a Feistel network splitting the block into halves, AES processes all 128 bits simultaneously using a Substitution-Permutation Network (SPN). The input bytes are arranged column-wise into the state matrix.',
    formula: 'State[r,c] = input[r + 4c] for 0 ≤ r,c < 4'
  },
  keyAddition: {
    title: 'Key Addition Layer (AddRoundKey)',
    description: 'A 128-bit round key derived from the main cipher key is XORed with the current state. This is called "Key Whitening" when applied before the first round. Each round uses a different subkey generated by the AES Key Schedule. This operation provides the actual encryption by mixing the key material with the data.',
    formula: 'State\'[i,j] = State[i,j] ⊕ RoundKey[i,j]'
  },
  rounds: {
    title: 'AES Round Structure',
    description: 'The number of rounds depends on key size: 10 rounds for 128-bit keys, 12 rounds for 192-bit keys, and 14 rounds for 256-bit keys. Each round (except the final round) consists of four transformations applied in sequence: SubBytes → ShiftRows → MixColumns → AddRoundKey. The final round omits MixColumns to make encryption/decryption symmetric.',
    formula: 'Nr = 10, 12, or 14 for key sizes 128, 192, 256 bits'
  },
  subBytes: {
    title: 'Byte Substitution Layer (SubBytes)',
    description: 'The confusion layer of AES. Each byte of the state is independently substituted using a fixed 8-bit S-box. The S-box is constructed by: (1) computing the multiplicative inverse in GF(2⁸) with irreducible polynomial x⁸+x⁴+x³+x+1, then (2) applying an affine transformation. This nonlinear transformation prevents algebraic attacks.',
    formula: 'S(a) = Affine(a⁻¹) in GF(2⁸)'
  },
  shiftRows: {
    title: 'ShiftRows Layer',
    description: 'The first diffusion layer. Each row of the state matrix is cyclically shifted by a different offset: Row 0 is not shifted, Row 1 shifts left by 1, Row 2 by 2, and Row 3 by 3 positions. This ensures that columns of the output state are composed of bytes from different columns of the input state.',
    formula: 'State\'[r,c] = State[r, (c + r) mod 4]'
  },
  mixColumns: {
    title: 'MixColumns Layer',
    description: 'The second diffusion layer providing high diffusion. Each column is treated as a polynomial over GF(2⁸) and multiplied by the fixed polynomial c(x) = 03·x³ + 01·x² + 01·x + 02 modulo x⁴+1. This mixes the four bytes in each column, ensuring that changing one input byte affects all four output bytes.',
    formula: 'State\'(x) = c(x) ⊗ State(x) mod (x⁴ + 1)'
  },
  ciphertext: {
    title: '128-bit Ciphertext',
    description: 'The final encrypted state after all rounds complete. The final round deliberately omits MixColumns, which makes the encryption and decryption algorithms more symmetric. The ciphertext bytes are read column-wise from the final state matrix.',
    formula: 'output[r + 4c] = State[r,c] for 0 ≤ r,c < 4'
  }
};

export default function AESDiagram({ onHover }) {
  return (
    <div className="diagram-container">
      <FlowRow>
        <DiagramNode type="plaintext" info={aesInfo.plaintext} onHover={onHover}>
          128-bit Plaintext
        </DiagramNode>
      </FlowRow>
      
      <Arrow direction="down" />
      
      <FlowRow>
        <DiagramNode type="key" info={aesInfo.keyAddition} onHover={onHover}>
          Initial Key Addition
        </DiagramNode>
      </FlowRow>
      
      <Arrow direction="down" />
      
      {/* Main Round Box */}
      <div 
        className="bg-slate-300/50 rounded-xl p-4 border-2 border-dashed border-slate-400 cursor-pointer hover:bg-slate-300/70 transition-colors"
        onMouseEnter={() => onHover && onHover(aesInfo.rounds)}
      >
        <div className="text-center text-xs text-slate-600 font-semibold mb-3">
          ROUNDS (×9, ×11, or ×13)
        </div>
        <div className="flex flex-col gap-2">
          <DiagramNode type="internal" info={aesInfo.subBytes} onHover={onHover}>
            SubBytes (S-Box)
          </DiagramNode>
          <Arrow direction="down" />
          <DiagramNode type="internal" info={aesInfo.shiftRows} onHover={onHover}>
            ShiftRows
          </DiagramNode>
          <Arrow direction="down" />
          <DiagramNode type="internal" info={aesInfo.mixColumns} onHover={onHover}>
            MixColumns
          </DiagramNode>
          <Arrow direction="down" />
          <DiagramNode type="key" info={aesInfo.keyAddition} onHover={onHover}>
            AddRoundKey
          </DiagramNode>
        </div>
      </div>
      
      <Arrow direction="down" />
      
      {/* Final Round */}
      <div className="bg-amber-100/50 rounded-xl p-4 border-2 border-dashed border-amber-400">
        <div className="text-center text-xs text-amber-700 font-semibold mb-3">
          FINAL ROUND
        </div>
        <div className="flex flex-col gap-2">
          <DiagramNode type="internal" info={aesInfo.subBytes} onHover={onHover}>
            SubBytes (S-Box)
          </DiagramNode>
          <Arrow direction="down" />
          <DiagramNode type="internal" info={aesInfo.shiftRows} onHover={onHover}>
            ShiftRows
          </DiagramNode>
          <Arrow direction="down" />
          <DiagramNode type="key" info={aesInfo.keyAddition} onHover={onHover}>
            AddRoundKey
          </DiagramNode>
        </div>
      </div>
      
      <Arrow direction="down" />
      
      <FlowRow>
        <DiagramNode type="ciphertext" info={aesInfo.ciphertext} onHover={onHover}>
          128-bit Ciphertext
        </DiagramNode>
      </FlowRow>
    </div>
  );
}
